
using Dto.ApiWebDtos.GeneralDtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.StaticValues
{
    public class CountryList
    {
        public static List<SelectListOption> Countries = new List<SelectListOption>()
        {
            new SelectListOption { ID = 1, Value = "Afghanistan" },
            new SelectListOption { ID = 2, Value = "Åland Islands" },
            new SelectListOption { ID = 3, Value = "Albania" },
            new SelectListOption { ID = 4, Value = "Algeria" },
            new SelectListOption { ID = 5, Value = "American Samoa" },
            new SelectListOption { ID = 6, Value = "Andorra" },
            new SelectListOption { ID = 7, Value = "Angola" },
            new SelectListOption { ID = 8, Value = "Anguilla" },
            new SelectListOption { ID = 9, Value = "Antarctica" },
            new SelectListOption { ID = 10, Value = "Antigua and Barbuda" },
            new SelectListOption { ID = 11, Value = "Argentina" },
            new SelectListOption { ID = 12, Value = "Armenia" },
            new SelectListOption { ID = 13, Value = "Aruba" },
            new SelectListOption { ID = 14, Value = "Australia" },
            new SelectListOption { ID = 15, Value = "Austria" },
            new SelectListOption { ID = 16, Value = "Azerbaijan" },
            new SelectListOption { ID = 17, Value = "Bahamas" },
            new SelectListOption { ID = 18, Value = "Bahrain" },
            new SelectListOption { ID = 19, Value = "Bangladesh" },
            new SelectListOption { ID = 20, Value = "Barbados" },
            new SelectListOption { ID = 21, Value = "Belarus" },
            new SelectListOption { ID = 22, Value = "Belgium" },
            new SelectListOption { ID = 23, Value = "Belize" },
            new SelectListOption { ID = 24, Value = "Benin" },
            new SelectListOption { ID = 25, Value = "Bermuda" },
            new SelectListOption { ID = 26, Value = "Bhutan" },
            new SelectListOption { ID = 27, Value = "Bolivia (Plurinational State of)" },
            new SelectListOption { ID = 28, Value = "Bonaire, Sint Eustatius and Saba" },
            new SelectListOption { ID = 29, Value = "Bosnia and Herzegovina" },
            new SelectListOption { ID = 30, Value = "Botswana" },
            new SelectListOption { ID = 31, Value = "Bouvet Island" },
            new SelectListOption { ID = 32, Value = "Brazil" },
            new SelectListOption { ID = 33, Value = "British Indian Ocean Territory" },
            new SelectListOption { ID = 34, Value = "Brunei Darussalam" },
            new SelectListOption { ID = 35, Value = "Bulgaria" },
            new SelectListOption { ID = 36, Value = "Burkina Faso" },
            new SelectListOption { ID = 37, Value = "Burundi" },
            new SelectListOption { ID = 38, Value = "Cabo Verde" },
            new SelectListOption { ID = 39, Value = "Cambodia" },
            new SelectListOption { ID = 40, Value = "Cameroon" },
            new SelectListOption { ID = 41, Value = "Canada" },
            new SelectListOption { ID = 42, Value = "Cayman Islands" },
            new SelectListOption { ID = 43, Value = "Central African Republic" },
            new SelectListOption { ID = 44, Value = "Chad" },
            new SelectListOption { ID = 45, Value = "Chile" },
            new SelectListOption { ID = 46, Value = "China" },
            new SelectListOption { ID = 47, Value = "Christmas Island" },
            new SelectListOption { ID = 48, Value = "Cocos (Keeling) Islands" },
            new SelectListOption { ID = 49, Value = "Colombia" },
            new SelectListOption { ID = 50, Value = "Comoros" },
            new SelectListOption { ID = 51, Value = "Congo" },
            new SelectListOption { ID = 52, Value = "Congo (Democratic Republic of the)" },
            new SelectListOption { ID = 53, Value = "Cook Islands" },
            new SelectListOption { ID = 54, Value = "Costa Rica" },
            new SelectListOption { ID = 55, Value = "Côte d'Ivoire" },
            new SelectListOption { ID = 56, Value = "Croatia" },
            new SelectListOption { ID = 57, Value = "Cuba" },
            new SelectListOption { ID = 58, Value = "Curaçao" },
            new SelectListOption { ID = 59, Value = "Cyprus" },
            new SelectListOption { ID = 60, Value = "Czechia" },
            new SelectListOption { ID = 61, Value = "Denmark" },
            new SelectListOption { ID = 62, Value = "Djibouti" },
            new SelectListOption { ID = 63, Value = "Dominica" },
            new SelectListOption { ID = 64, Value = "Dominican Republic" },
            new SelectListOption { ID = 65, Value = "Ecuador" },
            new SelectListOption { ID = 66, Value = "Egypt" },
            new SelectListOption { ID = 67, Value = "El Salvador" },
            new SelectListOption { ID = 68, Value = "Equatorial Guinea" },
            new SelectListOption { ID = 69, Value = "Eritrea" },
            new SelectListOption { ID = 70, Value = "Estonia" },
            new SelectListOption { ID = 71, Value = "Ethiopia" },
            new SelectListOption { ID = 72, Value = "Falkland Islands (Malvinas)" },
            new SelectListOption { ID = 73, Value = "Faroe Islands" },
            new SelectListOption { ID = 74, Value = "Fiji" },
            new SelectListOption { ID = 75, Value = "Finland" },
            new SelectListOption { ID = 76, Value = "France" },
            new SelectListOption { ID = 77, Value = "French Guiana" },
            new SelectListOption { ID = 78, Value = "French Polynesia" },
            new SelectListOption { ID = 79, Value = "French Southern Territories" },
            new SelectListOption { ID = 80, Value = "Gabon" },
            new SelectListOption { ID = 81, Value = "Gambia" },
            new SelectListOption { ID = 82, Value = "Georgia" },
            new SelectListOption { ID = 83, Value = "Germany" },
            new SelectListOption { ID = 84, Value = "Ghana" },
            new SelectListOption { ID = 85, Value = "Gibraltar" },
            new SelectListOption { ID = 86, Value = "Greece" },
            new SelectListOption { ID = 87, Value = "Greenland" },
            new SelectListOption { ID = 88, Value = "Grenada" },
            new SelectListOption { ID = 89, Value = "Guadeloupe" },
            new SelectListOption { ID = 90, Value = "Guam" },
            new SelectListOption { ID = 91, Value = "Guatemala" },
            new SelectListOption { ID = 92, Value = "Guernsey" },
            new SelectListOption { ID = 93, Value = "Guinea" },
            new SelectListOption { ID = 94, Value = "Guinea-Bissau" },
            new SelectListOption { ID = 95, Value = "Guyana" },
            new SelectListOption { ID = 96, Value = "Haiti" },
            new SelectListOption { ID = 97, Value = "Heard Island and McDonald Islands" },
            new SelectListOption { ID = 98, Value = "Holy See" },
            new SelectListOption { ID = 99, Value = "Honduras" },
            new SelectListOption { ID = 100, Value = "Hong Kong" },
            new SelectListOption { ID = 101, Value = "Hungary" },
            new SelectListOption { ID = 102, Value = "Iceland" },
            new SelectListOption { ID = 103, Value = "India" },
            new SelectListOption { ID = 104, Value = "Indonesia" },
            new SelectListOption { ID = 105, Value = "Iran (Islamic Republic of)" },
            new SelectListOption { ID = 106, Value = "Iraq" },
            new SelectListOption { ID = 107, Value = "Ireland" },
            new SelectListOption { ID = 108, Value = "Isle of Man" },
            new SelectListOption { ID = 109, Value = "Israel" },
            new SelectListOption { ID = 110, Value = "Italy" },
            new SelectListOption { ID = 111, Value = "Jamaica" },
            new SelectListOption { ID = 112, Value = "Japan" },
            new SelectListOption { ID = 113, Value = "Jersey" },
            new SelectListOption { ID = 114, Value = "Jordan" },
            new SelectListOption { ID = 115, Value = "Kazakhstan" },
            new SelectListOption { ID = 116, Value = "Kenya" },
            new SelectListOption { ID = 117, Value = "Kiribati" },
            new SelectListOption { ID = 118, Value = "Korea (Democratic People's Republic of)" },
            new SelectListOption { ID = 119, Value = "Korea (Republic of)" },
            new SelectListOption { ID = 120, Value = "Kuwait" },
            new SelectListOption { ID = 121, Value = "Kyrgyzstan" },
            new SelectListOption { ID = 122, Value = "Lao People's Democratic Republic" },
            new SelectListOption { ID = 123, Value = "Latvia" },
            new SelectListOption { ID = 124, Value = "Lebanon" },
            new SelectListOption { ID = 125, Value = "Lesotho" },
            new SelectListOption { ID = 126, Value = "Liberia" },
            new SelectListOption { ID = 127, Value = "Libya" },
            new SelectListOption { ID = 128, Value = "Liechtenstein" },
            new SelectListOption { ID = 129, Value = "Lithuania" },
            new SelectListOption { ID = 130, Value = "Luxembourg" },
            new SelectListOption { ID = 131, Value = "Macao" },
            new SelectListOption { ID = 132, Value = "Macedonia (the former Yugoslav Republic of)" },
            new SelectListOption { ID = 133, Value = "Madagascar" },
            new SelectListOption { ID = 134, Value = "Malawi" },
            new SelectListOption { ID = 135, Value = "Malaysia" },
            new SelectListOption { ID = 136, Value = "Maldives" },
            new SelectListOption { ID = 137, Value = "Mali" },
            new SelectListOption { ID = 138, Value = "Malta" },
            new SelectListOption { ID = 139, Value = "Marshall Islands" },
            new SelectListOption { ID = 140, Value = "Martinique" },
            new SelectListOption { ID = 141, Value = "Mauritania" },
            new SelectListOption { ID = 142, Value = "Mauritius" },
            new SelectListOption { ID = 143, Value = "Mayotte" },
            new SelectListOption { ID = 144, Value = "Mexico" },
            new SelectListOption { ID = 145, Value = "Micronesia (Federated States of)" },
            new SelectListOption { ID = 146, Value = "Moldova (Republic of)" },
            new SelectListOption { ID = 147, Value = "Monaco" },
            new SelectListOption { ID = 148, Value = "Mongolia" },
            new SelectListOption { ID = 149, Value = "Montenegro" },
            new SelectListOption { ID = 150, Value = "Montserrat" },
            new SelectListOption { ID = 151, Value = "Morocco" },
            new SelectListOption { ID = 152, Value = "Mozambique" },
            new SelectListOption { ID = 153, Value = "Myanmar" },
            new SelectListOption { ID = 154, Value = "Namibia" },
            new SelectListOption { ID = 155, Value = "Nauru" },
            new SelectListOption { ID = 156, Value = "Nepal" },
            new SelectListOption { ID = 157, Value = "Netherlands" },
            new SelectListOption { ID = 158, Value = "New Caledonia" },
            new SelectListOption { ID = 159, Value = "New Zealand" },
            new SelectListOption { ID = 160, Value = "Nicaragua" },
            new SelectListOption { ID = 161, Value = "Niger" },
            new SelectListOption { ID = 162, Value = "Nigeria" },
            new SelectListOption { ID = 163, Value = "Niue" },
            new SelectListOption { ID = 164, Value = "Norfolk Island" },
            new SelectListOption { ID = 165, Value = "Northern Mariana Islands" },
            new SelectListOption { ID = 166, Value = "Norway" },
            new SelectListOption { ID = 167, Value = "Oman" },
            new SelectListOption { ID = 168, Value = "Pakistan" },
            new SelectListOption { ID = 169, Value = "Palau" },
            new SelectListOption { ID = 170, Value = "Palestine, State of" },
            new SelectListOption { ID = 171, Value = "Panama" },
            new SelectListOption { ID = 172, Value = "Papua New Guinea" },
            new SelectListOption { ID = 173, Value = "Paraguay" },
            new SelectListOption { ID = 174, Value = "Peru" },
            new SelectListOption { ID = 175, Value = "Philippines" },
            new SelectListOption { ID = 176, Value = "Pitcairn" },
            new SelectListOption { ID = 177, Value = "Poland" },
            new SelectListOption { ID = 178, Value = "Portugal" },
            new SelectListOption { ID = 179, Value = "Puerto Rico" },
            new SelectListOption { ID = 180, Value = "Qatar" },
            new SelectListOption { ID = 181, Value = "Réunion" },
            new SelectListOption { ID = 182, Value = "Romania" },
            new SelectListOption { ID = 183, Value = "Russian Federation" },
            new SelectListOption { ID = 184, Value = "Rwanda" },
            new SelectListOption { ID = 185, Value = "Saint Barthélemy" },
            new SelectListOption { ID = 186, Value = "Saint Helena, Ascension and Tristan da Cunha" },
            new SelectListOption { ID = 187, Value = "Saint Kitts and Nevis" },
            new SelectListOption { ID = 188, Value = "Saint Lucia" },
            new SelectListOption { ID = 189, Value = "Saint Martin (French part)" },
            new SelectListOption { ID = 190, Value = "Saint Pierre and Miquelon" },
            new SelectListOption { ID = 191, Value = "Saint Vincent and the Grenadines" },
            new SelectListOption { ID = 192, Value = "Samoa" },
            new SelectListOption { ID = 193, Value = "San Marino" },
            new SelectListOption { ID = 194, Value = "Sao Tome and Principe" },
            new SelectListOption { ID = 195, Value = "Saudi Arabia" },
            new SelectListOption { ID = 196, Value = "Senegal" },
            new SelectListOption { ID = 197, Value = "Serbia" },
            new SelectListOption { ID = 198, Value = "Seychelles" },
            new SelectListOption { ID = 199, Value = "Sierra Leone" },
            new SelectListOption { ID = 200, Value = "Singapore" },
            new SelectListOption { ID = 201, Value = "Sint Maarten (Dutch part)" },
            new SelectListOption { ID = 202, Value = "Slovakia" },
            new SelectListOption { ID = 203, Value = "Slovenia" },
            new SelectListOption { ID = 204, Value = "Solomon Islands" },
            new SelectListOption { ID = 205, Value = "Somalia" },
            new SelectListOption { ID = 206, Value = "South Africa" },
            new SelectListOption { ID = 207, Value = "South Georgia and the South Sandwich Islands" },
            new SelectListOption { ID = 208, Value = "South Sudan" },
            new SelectListOption { ID = 209, Value = "Spain" },
            new SelectListOption { ID = 210, Value = "Sri Lanka" },
            new SelectListOption { ID = 211, Value = "Sudan" },
            new SelectListOption { ID = 212, Value = "Suriname" },
            new SelectListOption { ID = 213, Value = "Svalbard and Jan Mayen" },
            new SelectListOption { ID = 214, Value = "Swaziland" },
            new SelectListOption { ID = 215, Value = "Sweden" },
            new SelectListOption { ID = 216, Value = "Switzerland" },
            new SelectListOption { ID = 217, Value = "Syrian Arab Republic" },
            new SelectListOption { ID = 218, Value = "Taiwan, Province of China" },
            new SelectListOption { ID = 219, Value = "Tajikistan" },
            new SelectListOption { ID = 220, Value = "Tanzania, United Republic of" },
            new SelectListOption { ID = 221, Value = "Thailand" },
            new SelectListOption { ID = 222, Value = "Timor-Leste" },
            new SelectListOption { ID = 223, Value = "Togo" },
            new SelectListOption { ID = 224, Value = "Tokelau" },
            new SelectListOption { ID = 225, Value = "Tonga" },
            new SelectListOption { ID = 226, Value = "Trinidad and Tobago" },
            new SelectListOption { ID = 227, Value = "Tunisia" },
            new SelectListOption { ID = 228, Value = "Turkey" },
            new SelectListOption { ID = 229, Value = "Turkmenistan" },
            new SelectListOption { ID = 230, Value = "Turks and Caicos Islands" },
            new SelectListOption { ID = 231, Value = "Tuvalu" },
            new SelectListOption { ID = 232, Value = "Uganda" },
            new SelectListOption { ID = 233, Value = "Ukraine" },
            new SelectListOption { ID = 234, Value = "United Arab Emirates" },
            new SelectListOption { ID = 235, Value = "United Kingdom of Great Britain and Northern Ireland" },
            new SelectListOption { ID = 236, Value = "United States of America" },
            new SelectListOption { ID = 237, Value = "United States Minor Outlying Islands" },
            new SelectListOption { ID = 238, Value = "Uruguay" },
            new SelectListOption { ID = 239, Value = "Uzbekistan" },
            new SelectListOption { ID = 240, Value = "Vanuatu" },
            new SelectListOption { ID = 241, Value = "Venezuela (Bolivarian Republic of)" },
            new SelectListOption { ID = 242, Value = "Viet Nam" },
            new SelectListOption { ID = 243, Value = "Virgin Islands (British)" },
            new SelectListOption { ID = 244, Value = "Virgin Islands (U.S.)" },
            new SelectListOption { ID = 245, Value = "Wallis and Futuna" },
            new SelectListOption { ID = 246, Value = "Western Sahara" },
            new SelectListOption { ID = 247, Value = "Yemen" },
            new SelectListOption { ID = 248, Value = "Zambia" },
            new SelectListOption { ID = 249, Value = "Zimbabwe" }
        };

        public static string GetValue(int id)
        {
            return Countries.FirstOrDefault(x => x.ID == id).Value;
        }
    }
}
